---
version: "3.9"

services:

  devopsdb:
    image: ashraysambu/sam:db

    ports:
      - "3306:3306"

    deploy:
      replicas: 3

    networks:
      - my-net

  application:
    image: ashraysambu/sam:app

    ports:
      - "1111:8080"

    depends_on:
      - devopsdb

    deploy:
      replicas: 3

    networks:
      - my-net

networks:

  my-net:
    driver: overlay
